FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block collectd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='collectd') }}

{% set collectd_packages = [
    ''
] %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
  {% set collectd_packages = collectd_packages + [
      'libtool-ltdl',
      'libtool-ltdl-devel'
  ] %}

{% endif %}
{{ macros.install_packages(collectd_packages | customizable("packages")) }}
COPY collectd-disk-5.7.2-3.el7.ppc64le.rpm /
COPY collectd-5.7.2-3.el7.ppc64le.rpm /
RUN yum -y install /collectd-5.7.2-3.el7.ppc64le.rpm  /collectd-disk-5.7.2-3.el7.ppc64le.rpm
COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chown -R collectd /var/lib/collectd \
    && chown -R collectd /etc/collectd* \
    && chown -R collectd /var/run/

{% block collectd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER collectd
